<div class="tabcontrols">
  <button class="tabcontrol" onclick="openTab(event, 'en')" id="defaultLang">English</button>
  <button class="tabcontrol" onclick="openTab(event, 'lm')">Lorem</button>
</div>

<div id="en" class="pledge">
  <p>
    We, the undersigned, believe that communities are only truly inclusive if everyone is able to participate.
    Now that video conferencing is widely available,
    we believe that no one should be shut out or left behind
    because they cannot afford to travel,
    are unable to obtain a visa,
    have health concerns,
    or need to look after family members.
    Accordingly,
    we pledge that we will not take part in any conference
    that does not provide an option for remote attendance
    unless required to do so as a condition of employment.
  </p>
</div>

<div id="lm" class="pledge">
  <p>
    Lorem ipsum dolor sit amet,
    consectetur adipiscing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident,
    sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
</div>
