<div class="signup">
  <form action="/submission/" method="post">
    <table>
      <tr>
        <th colspan="2">Sign the pledge</th>
      </tr>
      <tr>
        <th><label for="fullname">Name*</label></th>
        <td><input type="text" id="fullname" name="fullname"/></td>
        <th><label for="email">Email*</label></th>
        <td><input type="text" id="email" name="email"/></td>
      </tr>
      <tr>
        <th><label for="country">Country</label></th>
        <td><input type="text" id="country" name="country"/></td>
        <th><label for="affiliation">Affiliation</label></th>
        <td><input type="text" id="affiliation" name="affiliation"/></td>
      </tr>
      <tr>
        <td colspan="2">(*) required fields</td>
      </tr>
    </table>
    <p>
      <input type="submit"/>
    </p>
  </form>
</div>
